name: ExplosionRegen
version: 2.6.0
main: net.starlegacy.explosionregen.ExplosionRegenPlugin
authors: ["MicleBrick", "SijmenSchoon", "rsammelson", "DeJayDev"]
api-version: 1.15
commands:
  regen:
    permission: explosionregen.regen
